{
 "title": "Virtual Hosts (Network Requests)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "containers",
    "label": "Containers",
    "query": "label_values(promtail_custom_requests, container_name)"
   },
   {
    "name": "hosts",
    "label": "Virtual Hosts",
    "query": "label_values(promtail_custom_requests, http_host)"
   },
   { "name": "protos", "label": "Schema", "query": "http,https" },
   { "name": "methods", "label": "Method", "query": "POST,GET,PUT,PATCH,DELETE" },
   {
    "name": "codes",
    "label": "Status Codes",
    "query": "label_values(promtail_custom_requests, http_status_code)"
   },
   {
    "name": "useragent_types",
    "label": "Useragent Types",
    "query": "label_values(promtail_custom_requests, http_useragent_type)"
   }
  ]
 },
 "panels": [
  { "title": "All Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$hosts",
   "type": "grafana-piechart-panel",
   "description": "HTTP Response Codes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "hosts",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(http_status_code) (increase(promtail_custom_requests{container_name=~\"$containers\",http_status_code=~\"$codes\",http_method=~\"$methods\",http_proto=~\"$protos\",http_useragent_type=~\"$useragent_types\",http_host=~\"$hosts\"}[$__interval])) != 0",
     "legendFormat": "{{ http_status_code }}"
    }
   ]
  },
  {
   "title": "Successful Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(promtail_custom_requests{container_name=~\"$containers\",http_method=~\"$methods\",http_proto=~\"$protos\",http_useragent_type=~\"$useragent_types\",http_host=~\"$hosts\",http_status_code=\"200\"}[$__interval])) by(http_host)",
     "legendFormat": "{{ http_host }} requests"
    },
    {
     "expr": "sum(irate(promtail_custom_bytes_written{container_name=~\"$containers\",http_method=~\"$methods\",http_proto=~\"$protos\",http_useragent_type=~\"$useragent_types\",http_host=~\"$hosts\",http_status_code=\"200\"}[$__interval])) by(http_host)",
     "legendFormat": "{{ http_host }} bytes"
    }
   ]
  },
  {
   "title": "$hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "hosts",
   "collapsed": true,
   "panels": [
    {
     "title": "[$hosts] OK response duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(promtail_custom_request_duration_sum{container_name=~\"$containers\",http_method=~\"$methods\",http_proto=~\"$protos\",http_useragent_type=~\"$useragent_types\",http_host=~\"$hosts\",http_status_code=\"200\"}[$__interval])) by (page) != 0",
       "legendFormat": "{{ page }}"
      }
     ]
    },
    {
     "title": "[$hosts] status codes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(promtail_custom_requests{container_name=~\"$containers\",http_method=~\"$methods\",http_status_code=~\"$codes\",http_proto=~\"$protos\",http_useragent_type=~\"$useragent_types\",http_host=~\"$hosts\"}[$__interval])) by (container_name, page, http_status_code) != 0",
       "legendFormat": "{{ http_status_code }} [{{ container_name }}] {{ page }}"
      }
     ]
    },
    {
     "title": "[$hosts] successful throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(promtail_custom_requests{container_name=~\"$containers\",http_status_code=~\"$codes\",http_method=~\"$methods\",http_proto=~\"$protos\",http_host=~\"$hosts\",http_status_code=\"200\"}[$__interval])) by(container_name, http_host)",
       "legendFormat": "{{ container_name }} queries"
      },
      {
       "expr": "sum(irate(promtail_custom_bytes_written{container_name=~\"$containers\",http_status_code=~\"$codes\",http_method=~\"$methods\",http_proto=~\"$protos\",http_host=~\"$hosts\",http_status_code=\"200\"}[$__interval])) by(container_name, http_host)",
       "legendFormat": "{{ container_name }} bytes"
      }
     ]
    }
   ]
  }
 ]
}