{
 "title": "Network Requests",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "query": "label_values(promtail_custom_requests, http_host)"
   }
  ]
 },
 "panels": [
  { "title": "All Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$hosts",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "repeat": "hosts",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(http_status_code) (promtail_custom_requests{container_name=\"switchboard\",http_host=~\"$hosts\"})",
     "legendFormat": "{{ http_status_code }}"
    }
   ]
  },
  {
   "title": "$hosts",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(http_status_code) (promtail_custom_requests{container_name=\"switchboard\",http_host=~\"$hosts\"})",
     "legendFormat": "{{ http_status_code }}"
    }
   ]
  },
  {
   "title": "$hosts",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(http_status_code) (promtail_custom_requests{container_name=\"switchboard\",http_host=~\"$hosts\"})",
     "legendFormat": "{{ http_status_code }}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(http_host) (rate(promtail_custom_requests{container_name=\"switchboard\",http_host=~\"$hosts\"}[1m]))",
     "legendFormat": "{{ http_host }}"
    }
   ]
  },
  {
   "title": "$hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "hosts",
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Successful Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "sum (rate(promtail_custom_request_duration_sum{container_name=\"switchboard\",http_status_code=\"200\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "$host 200 OK successful requests"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(promtail_custom_request_duration_sum{container_name=\"switchboard\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "{{ http_status_code }}"
      }
     ]
    },
    {
     "title": "QPS by HTTP Status Code",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(promtail_custom_requests{container_name=\"switchboard\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "{{ http_status_code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Successful Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "sum (rate(promtail_custom_request_duration_sum{container_name=\"switchboard\",http_status_code=\"200\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "$host 200 OK successful requests"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(promtail_custom_request_duration_sum{container_name=\"switchboard\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "{{ http_status_code }}"
      }
     ]
    },
    {
     "title": "QPS by HTTP Status Code",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(promtail_custom_requests{container_name=\"switchboard\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "{{ http_status_code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Successful Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "sum (rate(promtail_custom_request_duration_sum{container_name=\"switchboard\",http_status_code=\"200\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "$host 200 OK successful requests"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(promtail_custom_request_duration_sum{container_name=\"switchboard\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "{{ http_status_code }}"
      }
     ]
    },
    {
     "title": "QPS by HTTP Status Code",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(promtail_custom_requests{container_name=\"switchboard\",http_host=~\"$hosts\"}[1m]))",
       "legendFormat": "{{ http_status_code }}"
      }
     ]
    }
   ]
  }
 ]
}